# Generated by Django 2.0.5 on 2019-01-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webshell_Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=200, verbose_name='host_ip')),
                ('op_user', models.CharField(max_length=200, verbose_name='op_user')),
                ('op_ip', models.CharField(max_length=200, verbose_name='op_ip')),
                ('log', models.CharField(max_length=200, verbose_name='log')),
                ('insert_time', models.CharField(max_length=200, verbose_name='insert_time')),
            ],
        ),
    ]
