"""empty message

Revision ID: 3a64d847a7c9
Revises: b7dca6de930b
Create Date: 2017-11-18 19:19:34.520261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a64d847a7c9'
down_revision = 'b7dca6de930b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attack', sa.Column('country', sa.String(length=128), nullable=True))
    op.add_column('entry', sa.Column('country', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'country')
    op.drop_column('attack', 'country')
    # ### end Alembic commands ###
