"""empty message

Revision ID: b7dca6de930b
Revises: 
Create Date: 2017-11-18 18:42:26.022147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dca6de930b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sip', sa.String(length=16), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('sport', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('cip', sa.String(length=16), nullable=True),
    sa.Column('useragent', sa.Text(), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('substatus', sa.Text(), nullable=True),
    sa.Column('win32status', sa.Text(), nullable=True),
    sa.Column('timetaken', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attack')
    op.drop_table('entry')
    # ### end Alembic commands ###
