const fs = require('fs')
const Parser = require('./index') // parser generated by pegjs --trace
const Tracer = require('pegjs-backtrace')

var file = ''
try {
  file = fs.readFileSync(process.argv[2], 'utf8')
} catch (e) {
  console.log(e)
  process.exit(0)
}

file.split('\n').forEach(function (text) {
  var tracer = new Tracer(text)

  try {
    var output = Parser.parse(text, { tracer })
    console.log(JSON.stringify(output))
  } catch (e) {
    console.log('FAIL:', text)
    console.log(tracer.getBacktraceString())
    process.exit(0)
  }
})