# Generated by Django 2.1.3 on 2019-01-01 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=32)),
                ('task_name', models.TextField()),
                ('task_filepath', models.CharField(max_length=32)),
                ('task_status', models.CharField(max_length=7)),
                ('task_addtime', models.DateTimeField(auto_now_add=True)),
                ('task_finishtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='webshell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=32)),
                ('webshell_filepath', models.TextField()),
                ('webshell_md5', models.CharField(max_length=32)),
                ('webshell_addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
